name: publish
on: [push]
jobs:
  publish-runpod-template-pytorch2-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the runpod-template-pytorch2 Docker image
        run: |
          docker build . --tag ghcr.io/kesar/runpod-template-pytorch2:latest
          docker push ghcr.io/kesar/runpod-template-pytorch2:latest
