name: publish
on: [push]
jobs:
  publish-runpod-python37-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}
      - name: Build the runpod-python37 Docker image
        run: |
          docker build . --tag ghcr.io/youssefabdelm/runpod-python37:latest
          docker push ghcr.io/youssefabdelm/runpod-python37:latest
